// Code generated by wiregenx; DO NOT EDIT.
package container

import (
	"example/async"
	"example/config"
	"example/database"
	"example/http"
	"example/service"
	"example/websocket"
	"fmt"
)

type AsyncContainer struct {
	config      *config.Config
	db          *database.DB
	userService *service.UserService
	app         *async.App
}

func NewAsyncContainer() *AsyncContainer {
	c := &AsyncContainer{}

	c.config = config.NewConfig()

	var err error
	c.db, err = database.NewDB(c.config)
	if err != nil {
		panic(fmt.Sprintf("wiregenx: database.NewDB: %s", err))
	}

	c.userService = service.NewUserService(c.db)

	c.app = async.NewApp(c.config, c.userService)

	return c
}

func (c *AsyncContainer) Config() *config.Config {
	return c.config
}

func (c *AsyncContainer) DB() *database.DB {
	return c.db
}

func (c *AsyncContainer) UserService() *service.UserService {
	return c.userService
}

func (c *AsyncContainer) App() *async.App {
	return c.app
}

type HttpContainer struct {
	config      *config.Config
	db          *database.DB
	userService *service.UserService
	app         *http.App
}

func NewHttpContainer() *HttpContainer {
	c := &HttpContainer{}

	c.config = config.NewConfig()

	var err error
	c.db, err = database.NewDB(c.config)
	if err != nil {
		panic(fmt.Sprintf("wiregenx: database.NewDB: %s", err))
	}

	c.userService = service.NewUserService(c.db)

	c.app = http.NewApp(c.config, c.userService)

	return c
}

func (c *HttpContainer) Config() *config.Config {
	return c.config
}

func (c *HttpContainer) DB() *database.DB {
	return c.db
}

func (c *HttpContainer) UserService() *service.UserService {
	return c.userService
}

func (c *HttpContainer) App() *http.App {
	return c.app
}

type WebsocketContainer struct {
	config *config.Config
	db     *database.DB
	app    *websocket.App
}

func NewWebsocketContainer() *WebsocketContainer {
	c := &WebsocketContainer{}

	c.config = config.NewConfig()

	var err error
	c.db, err = database.NewDB(c.config)
	if err != nil {
		panic(fmt.Sprintf("wiregenx: database.NewDB: %s", err))
	}

	c.app = websocket.NewApp(c.config, c.db)

	return c
}

func (c *WebsocketContainer) Config() *config.Config {
	return c.config
}

func (c *WebsocketContainer) DB() *database.DB {
	return c.db
}

func (c *WebsocketContainer) App() *websocket.App {
	return c.app
}
