package internal

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

func renderWireProviders(outPkg string, funcs []InjectFunc) ([]byte, error) {
	// Sort for stable output
	sort.Slice(funcs, func(i, j int) bool {
		if funcs[i].ImportPath == funcs[j].ImportPath {
			return funcs[i].FuncName < funcs[j].FuncName
		}
		return funcs[i].ImportPath < funcs[j].ImportPath
	})

	// Build imports with aliases (avoid collisions)
	type imp struct {
		Path  string
		Alias string
	}
	imports := []imp{{Path: "github.com/google/wire", Alias: ""}}

	aliasByPath := map[string]string{}
	usedAlias := map[string]bool{"wire": true}

	// create alias from last segment, dedupe with suffix
	makeAlias := func(path string) string {
		seg := path
		if idx := strings.LastIndex(seg, "/"); idx >= 0 {
			seg = seg[idx+1:]
		}
		seg = sanitizeIdent(seg)
		if seg == "" {
			seg = "pkg"
		}
		a := seg
		for k := 2; usedAlias[a]; k++ {
			a = fmt.Sprintf("%s%d", seg, k)
		}
		usedAlias[a] = true
		return a
	}

	for _, f := range funcs {
		if f.ImportPath == "" {
			continue
		}
		if _, ok := aliasByPath[f.ImportPath]; ok {
			continue
		}
		al := makeAlias(f.ImportPath)
		aliasByPath[f.ImportPath] = al
		imports = append(imports, imp{Path: f.ImportPath, Alias: al})
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by wireinjectgen; DO NOT EDIT.\n")
	b.WriteString("package " + outPkg + "\n\n")

	// imports
	b.WriteString("import (\n")
	for _, im := range imports {
		if im.Alias == "" {
			b.WriteString(fmt.Sprintf("\t%q\n", im.Path))
		} else {
			b.WriteString(fmt.Sprintf("\t%s %q\n", im.Alias, im.Path))
		}
	}
	b.WriteString(")\n\n")

	// ProviderSet
	b.WriteString("var ProviderSet = wire.NewSet(\n")
	for _, f := range funcs {
		al := aliasByPath[f.ImportPath]
		if al == "" {
			// Shouldn't happen because we create alias for every import path
			continue
		}
		b.WriteString(fmt.Sprintf("\t%s.%s,\n", al, f.FuncName))
	}
	b.WriteString(")\n")

	return b.Bytes(), nil
}
