package pkg

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// renderContainer generates a complete DI container Go source file.
func renderContainer(outPkg string, providers []Provider) ([]byte, error) {
	// Separate singletons and prototypes
	var singletons, prototypes []Provider
	for _, p := range providers {
		if p.Scope == ScopePrototype {
			prototypes = append(prototypes, p)
		} else {
			singletons = append(singletons, p)
		}
	}

	hasFactory := false
	for _, p := range singletons {
		if p.IsFactory {
			hasFactory = true
			break
		}
	}

	// Collect all import paths needed
	allImports := collectImports(providers, hasFactory)

	// Build import aliases
	aliases, importLines := buildImportAliases(allImports)

	// Build provider type map for resolving dependencies
	typeToProvider := make(map[string]*Provider)
	for i := range providers {
		typeToProvider[providers[i].ReturnType.FullName()] = &providers[i]
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by wiregenx; DO NOT EDIT.\n")
	b.WriteString("package " + outPkg + "\n\n")

	// Imports
	if len(importLines) > 0 {
		b.WriteString("import (\n")
		for _, line := range importLines {
			b.WriteString("\t" + line + "\n")
		}
		b.WriteString(")\n\n")
	}

	// Container struct
	b.WriteString("type Container struct {\n")
	for _, p := range singletons {
		fieldName := singletonFieldName(p)
		typStr := renderType(p.ReturnType, aliases)
		b.WriteString(fmt.Sprintf("\t%s %s\n", fieldName, typStr))
	}
	b.WriteString("}\n\n")

	// New() constructor
	b.WriteString("func New() (*Container, error) {\n")
	b.WriteString("\tc := &Container{}\n\n")

	errDeclared := false
	for _, p := range singletons {
		fieldName := singletonFieldName(p)
		callExpr := renderFuncCall(p, aliases, typeToProvider)

		if p.IsFactory {
			if !errDeclared {
				b.WriteString(fmt.Sprintf("\tvar err error\n"))
				errDeclared = true
			}
			b.WriteString(fmt.Sprintf("\tc.%s, err = %s\n", fieldName, callExpr))
			b.WriteString(fmt.Sprintf("\tif err != nil {\n"))
			qualName := renderQualifiedName(p, aliases)
			b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"wiregenx: %s: %%w\", err)\n", qualName))
			b.WriteString(fmt.Sprintf("\t}\n\n"))
		} else {
			b.WriteString(fmt.Sprintf("\tc.%s = %s\n\n", fieldName, callExpr))
		}
	}

	b.WriteString("\treturn c, nil\n")
	b.WriteString("}\n\n")

	// Singleton getters
	for _, p := range singletons {
		methodName := getterMethodName(p)
		fieldName := singletonFieldName(p)
		typStr := renderType(p.ReturnType, aliases)
		b.WriteString(fmt.Sprintf("func (c *Container) %s() %s {\n", methodName, typStr))
		b.WriteString(fmt.Sprintf("\treturn c.%s\n", fieldName))
		b.WriteString("}\n\n")
	}

	// Prototype getters
	for _, p := range prototypes {
		methodName := getterMethodName(p)
		typStr := renderType(p.ReturnType, aliases)
		callExpr := renderFuncCall(p, aliases, typeToProvider)

		if p.IsFactory {
			b.WriteString(fmt.Sprintf("func (c *Container) %s() (%s, error) {\n", methodName, typStr))
			b.WriteString(fmt.Sprintf("\treturn %s\n", callExpr))
		} else {
			b.WriteString(fmt.Sprintf("func (c *Container) %s() %s {\n", methodName, typStr))
			b.WriteString(fmt.Sprintf("\treturn %s\n", callExpr))
		}
		b.WriteString("}\n\n")
	}

	// Format with gofmt
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		// Return unformatted with context for debugging
		return b.Bytes(), fmt.Errorf("gofmt failed: %w\n\ngenerated code:\n%s", err, b.String())
	}
	return formatted, nil
}

// collectImports gathers all unique import paths needed in the generated file.
func collectImports(providers []Provider, hasFactory bool) []string {
	seen := make(map[string]bool)
	var paths []string

	add := func(importPath string) {
		if importPath == "" || seen[importPath] {
			return
		}
		seen[importPath] = true
		paths = append(paths, importPath)
	}

	if hasFactory {
		add("fmt")
	}

	for _, p := range providers {
		// Import the provider's package (to call its function)
		add(p.ImportPath)

		// Import types referenced in return type
		add(p.ReturnType.ImportPath)

		// Import types referenced in params (needed for struct fields of prototypes)
		for _, param := range p.Params {
			add(param.ImportPath)
		}
	}

	return paths
}

// buildImportAliases creates collision-free aliases and formatted import lines.
func buildImportAliases(importPaths []string) (map[string]string, []string) {
	aliases := make(map[string]string) // import path → alias
	usedAliases := make(map[string]bool)

	var lines []string

	for _, path := range importPaths {
		seg := path
		if idx := strings.LastIndex(seg, "/"); idx >= 0 {
			seg = seg[idx+1:]
		}
		seg = sanitizeIdent(seg)
		if seg == "" {
			seg = "pkg"
		}

		alias := seg
		for k := 2; usedAliases[alias]; k++ {
			alias = fmt.Sprintf("%s%d", seg, k)
		}
		usedAliases[alias] = true
		aliases[path] = alias

		// If alias matches the last segment, no need for explicit alias in import
		lastSeg := path
		if idx := strings.LastIndex(lastSeg, "/"); idx >= 0 {
			lastSeg = lastSeg[idx+1:]
		}
		if alias == lastSeg {
			lines = append(lines, fmt.Sprintf("%q", path))
		} else {
			lines = append(lines, fmt.Sprintf("%s %q", alias, path))
		}
	}

	return aliases, lines
}

// renderType renders a TypeRef as Go source code using the given aliases.
func renderType(t TypeRef, aliases map[string]string) string {
	prefix := ""
	if t.IsPointer {
		prefix = "*"
	}
	if t.ImportPath != "" {
		alias := aliases[t.ImportPath]
		return prefix + alias + "." + t.TypeName
	}
	return prefix + t.TypeName
}

// renderFuncCall renders a provider function call with resolved arguments.
func renderFuncCall(p Provider, aliases map[string]string, typeToProvider map[string]*Provider) string {
	alias := aliases[p.ImportPath]
	funcRef := alias + "." + p.FuncName

	var args []string
	for _, param := range p.Params {
		depKey := param.FullName()
		dep := typeToProvider[depKey]
		if dep != nil && dep.Scope == ScopeSingleton {
			// Use singleton field
			args = append(args, "c."+singletonFieldName(*dep))
		} else if dep != nil && dep.Scope == ScopePrototype {
			// Call prototype getter
			args = append(args, "c."+getterMethodName(*dep)+"()")
		} else {
			args = append(args, "/* unresolved: "+depKey+" */")
		}
	}

	return funcRef + "(" + strings.Join(args, ", ") + ")"
}

// renderQualifiedName returns "alias.FuncName" for error messages.
func renderQualifiedName(p Provider, aliases map[string]string) string {
	alias := aliases[p.ImportPath]
	return alias + "." + p.FuncName
}

// singletonFieldName generates a private field name for a singleton provider.
func singletonFieldName(p Provider) string {
	// Use the return type's TypeName in lowerCamelCase
	name := p.ReturnType.TypeName
	if name == "" {
		name = p.FuncName
	}
	return lowerFirst(name)
}

// getterMethodName generates a public getter method name.
func getterMethodName(p Provider) string {
	name := p.ReturnType.TypeName
	if name == "" {
		name = p.FuncName
	}
	return upperFirst(name)
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	// Handle all-uppercase names like "DB", "ID" → "db", "id"
	r := []rune(s)
	allUpper := true
	for _, c := range r {
		if !unicode.IsUpper(c) && !unicode.IsDigit(c) {
			allUpper = false
			break
		}
	}
	if allUpper {
		return strings.ToLower(s)
	}
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
