package pkg

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// renderContainer generates a single Container from all providers (no @app mode).
func renderContainer(outPkg string, providers []Provider) ([]byte, error) {
	groups := []AppGroup{{Providers: providers}}
	return renderContainers(outPkg, groups)
}

// renderContainers generates one Container per AppGroup.
func renderContainers(outPkg string, groups []AppGroup) ([]byte, error) {
	// Collect all providers across groups for imports
	var allProviders []Provider
	for _, g := range groups {
		allProviders = append(allProviders, g.Providers...)
	}

	hasError := false
	for _, p := range allProviders {
		if p.ReturnsError {
			hasError = true
			break
		}
	}

	allImports := collectImports(allProviders, hasError)
	aliases, importLines := buildImportAliases(allImports)

	var b bytes.Buffer
	b.WriteString("// Code generated by wiregenx; DO NOT EDIT.\n")
	b.WriteString("package " + outPkg + "\n\n")

	if len(importLines) > 0 {
		b.WriteString("import (\n")
		for _, line := range importLines {
			b.WriteString("\t" + line + "\n")
		}
		b.WriteString(")\n\n")
	}

	for _, g := range groups {
		writeContainerSection(&b, g, aliases)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("gofmt failed: %w\n\ngenerated code:\n%s", err, b.String())
	}
	return formatted, nil
}

func writeContainerSection(b *bytes.Buffer, group AppGroup, aliases map[string]string) {
	containerName := "Container"
	constructorName := "New"
	if group.Name != "" {
		containerName = group.Name + "Container"
		constructorName = "New" + containerName
	}

	var singletons, prototypes []Provider
	for _, p := range group.Providers {
		if p.Scope == ScopePrototype {
			prototypes = append(prototypes, p)
		} else {
			singletons = append(singletons, p)
		}
	}

	typeToProvider := make(map[string]*Provider)
	for i := range group.Providers {
		typeToProvider[group.Providers[i].ReturnType.FullName()] = &group.Providers[i]
	}

	// Container struct
	b.WriteString(fmt.Sprintf("type %s struct {\n", containerName))
	for _, p := range singletons {
		fieldName := singletonFieldName(p)
		typStr := renderType(p.ReturnType, aliases)
		b.WriteString(fmt.Sprintf("\t%s %s\n", fieldName, typStr))
	}
	b.WriteString("}\n\n")

	// Constructor
	b.WriteString(fmt.Sprintf("func %s() *%s {\n", constructorName, containerName))
	b.WriteString(fmt.Sprintf("\tc := &%s{}\n\n", containerName))

	errDeclared := false
	for _, p := range singletons {
		fieldName := singletonFieldName(p)
		callExpr := renderFuncCall(p, aliases, typeToProvider)

		if p.ReturnsError {
			if !errDeclared {
				b.WriteString("\tvar err error\n")
				errDeclared = true
			}
			b.WriteString(fmt.Sprintf("\tc.%s, err = %s\n", fieldName, callExpr))
			b.WriteString("\tif err != nil {\n")
			qualName := renderQualifiedName(p, aliases)
			b.WriteString(fmt.Sprintf("\t\tpanic(fmt.Sprintf(\"wiregenx: %s: %%s\", err))\n", qualName))
			b.WriteString("\t}\n\n")
		} else {
			b.WriteString(fmt.Sprintf("\tc.%s = %s\n\n", fieldName, callExpr))
		}
	}

	b.WriteString("\treturn c\n")
	b.WriteString("}\n\n")

	// Singleton getters
	for _, p := range singletons {
		methodName := getterMethodName(p)
		fieldName := singletonFieldName(p)
		typStr := renderType(p.ReturnType, aliases)
		b.WriteString(fmt.Sprintf("func (c *%s) %s() %s {\n", containerName, methodName, typStr))
		b.WriteString(fmt.Sprintf("\treturn c.%s\n", fieldName))
		b.WriteString("}\n\n")
	}

	// Prototype getters
	for _, p := range prototypes {
		methodName := getterMethodName(p)
		typStr := renderType(p.ReturnType, aliases)
		callExpr := renderFuncCall(p, aliases, typeToProvider)

		b.WriteString(fmt.Sprintf("func (c *%s) %s() %s {\n", containerName, methodName, typStr))
		if p.ReturnsError {
			b.WriteString(fmt.Sprintf("\tv, err := %s\n", callExpr))
			b.WriteString("\tif err != nil {\n")
			qualName := renderQualifiedName(p, aliases)
			b.WriteString(fmt.Sprintf("\t\tpanic(fmt.Sprintf(\"wiregenx: %s: %%s\", err))\n", qualName))
			b.WriteString("\t}\n")
			b.WriteString("\treturn v\n")
		} else {
			b.WriteString(fmt.Sprintf("\treturn %s\n", callExpr))
		}
		b.WriteString("}\n\n")
	}
}

func collectImports(providers []Provider, hasError bool) []string {
	seen := make(map[string]bool)
	var paths []string

	add := func(importPath string) {
		if importPath == "" || seen[importPath] {
			return
		}
		seen[importPath] = true
		paths = append(paths, importPath)
	}

	if hasError {
		add("fmt")
	}

	for _, p := range providers {
		add(p.ImportPath)
		add(p.ReturnType.ImportPath)
		for _, param := range p.Params {
			add(param.Type.ImportPath)
		}
	}

	return paths
}

func buildImportAliases(importPaths []string) (map[string]string, []string) {
	aliases := make(map[string]string)
	usedAliases := make(map[string]bool)
	var lines []string

	for _, path := range importPaths {
		seg := path
		if idx := strings.LastIndex(seg, "/"); idx >= 0 {
			seg = seg[idx+1:]
		}
		seg = sanitizeIdent(seg)
		if seg == "" {
			seg = "pkg"
		}

		alias := seg
		for k := 2; usedAliases[alias]; k++ {
			alias = fmt.Sprintf("%s%d", seg, k)
		}
		usedAliases[alias] = true
		aliases[path] = alias

		lastSeg := path
		if idx := strings.LastIndex(lastSeg, "/"); idx >= 0 {
			lastSeg = lastSeg[idx+1:]
		}
		if alias == lastSeg {
			lines = append(lines, fmt.Sprintf("%q", path))
		} else {
			lines = append(lines, fmt.Sprintf("%s %q", alias, path))
		}
	}

	return aliases, lines
}

func renderType(t TypeRef, aliases map[string]string) string {
	prefix := ""
	if t.IsPointer {
		prefix = "*"
	}
	if t.ImportPath != "" {
		alias := aliases[t.ImportPath]
		return prefix + alias + "." + t.TypeName
	}
	return prefix + t.TypeName
}

func renderFuncCall(p Provider, aliases map[string]string, typeToProvider map[string]*Provider) string {
	alias := aliases[p.ImportPath]
	funcRef := alias + "." + p.FuncName

	var args []string
	for _, param := range p.Params {
		depKey := param.Type.FullName()
		dep := typeToProvider[depKey]
		if dep != nil && dep.Scope == ScopeSingleton {
			args = append(args, "c."+singletonFieldName(*dep))
		} else if dep != nil && dep.Scope == ScopePrototype {
			args = append(args, "c."+getterMethodName(*dep)+"()")
		} else {
			args = append(args, "/* unresolved: "+depKey+" */")
		}
	}

	return funcRef + "(" + strings.Join(args, ", ") + ")"
}

func renderQualifiedName(p Provider, aliases map[string]string) string {
	alias := aliases[p.ImportPath]
	return alias + "." + p.FuncName
}

func singletonFieldName(p Provider) string {
	name := p.ReturnType.TypeName
	if name == "" {
		name = p.FuncName
	}
	return lowerFirst(name)
}

func getterMethodName(p Provider) string {
	name := p.ReturnType.TypeName
	if name == "" {
		name = p.FuncName
	}
	return upperFirst(name)
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	allUpper := true
	for _, c := range r {
		if !unicode.IsUpper(c) && !unicode.IsDigit(c) {
			allUpper = false
			break
		}
	}
	if allUpper {
		return strings.ToLower(s)
	}
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
